### Módulo que contiene la función para importar librerías sin usar pip ###

def install_custom_requirements():

    # Importar módulos precargados de python
    import sys
    import subprocess
    import pkg_resources

    # Lista de paquetes a instalar (la primera vez que se ejecute desde Excel tardará unos minutos por reuqerir
    # de toda la instalación previa)
    packages_to_install = {'altair',
                           'altgraph',
                           'attrs',
                           'backoff',
                           'beautifulsoup4',
                           'bleach',
                           'boltons',
                           'bottle',
                           'bottle-websocket',
                           'bs4',
                           'cachetools',
                           'certifi',
                           'cffi',
                           'chardet',
                           'charset-normalizer',
                           'click',
                           'click-spinner',
                           'colorama',
                           'colorlog',
                           'cycler',
                           'dacite',
                           'datacommons',
                           'datacommons-pandas',
                           'datapane',
                           'decorator',
                           'defusedxml',
                           'dominate',
                           'Eel',
                           'entrypoints',
                           'et-xmlfile',
                           'face',
                           'fastjsonschema',
                           'ffn',
                           'fonttools',
                           'furl',
                           'future',
                           'gevent',
                           'gevent-websocket',
                           'glom',
                           'gower',
                           'greenlet',
                           'html5lib',
                           'httplib2',
                           'idna',
                           'importlib-resources',
                           'Jinja2',
                           'joblib',
                           'jsonschema',
                           'jupyter-client',
                           'jupyter-core',
                           'jupyterlab-pygments',
                           'kiwisolver',
                           'lxml',
                           'MarkupSafe',
                           'matplotlib',
                           'micawber',
                           'mimesis',
                           'mistune',
                           'monotonic',
                           'munch',
                           'mysql',
                           'mysql-connector-python',
                           'mysqlclient',
                           'nbclient',
                           'nbconvert',
                           'nbformat',
                           'nest-asyncio',
                           'numpy',
                           'oauth2client',
                           'oauthlib',
                           'openpyxl',
                           'orderedmultidict',
                           'packaging',
                           'pandas',
                           'pandas-datareader',
                           'pandocfilters',
                           'pefile',
                           'Pillow',
                           'plotly',
                           'posthog',
                           'prince',
                           'protobuf',
                           'pyarrow',
                           'pyasn1',
                           'pyasn1-modules',
                           'pycparser',
                           'pydantic',
                           'Pygments',
                           'pyinstaller',
                           'pyinstaller-hooks-contrib',
                           'PyMySQL',
                           'pyparsing',
                           'PyQt5',
                           'PyQt5-Qt5',
                           'PyQt5-sip',
                           'PyQt5-stubs',
                           'pyrsistent',
                           'python-dateutil',
                           'pytz',
                           'pywin32',
                           'pywin32-ctypes',
                           'PyYAML',
                           'pyzmq',
                           'requests',
                           'requests-oauthlib',
                           'requests-toolbelt',
                           'rsa',
                           'six',
                           'soupsieve',
                           'SQLAlchemy',
                           'stringcase',
                           'tabulate',
                           'tenacity',
                           'threadpoolctl',
                           'tinycss2',
                           'toolz',
                           'tornado',
                           'traitlets',
                           'typing-extensions',
                           'uritemplate',
                           'urllib3',
                           'validators',
                           'vega-datasets',
                           'webencodings',
                           'whichcraft',
                           'XlsxWriter',
                           'zipp',
                           'zope.event',
                           'zope.interface'}

    # Se comprueba si los paquetes de la lista están instalados o no, en caso contrario, proceder a ello
    required = packages_to_install
    installed = {pkg.key for pkg in pkg_resources.working_set}
    missing = required - installed

    if missing:
        python = sys.executable
        subprocess.check_call([python, '-m', 'pip', 'install', *missing], stdout=subprocess.DEVNULL)

